name: Build C++ Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
      
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config Release
          if [ $? -ne 0 ]; then
            echo "Build failed"
            exit 1
          fi
